version: "3"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./config:/config
    restart: always 
